version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run serve

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"